# Generated by Django 4.0.4 on 2022-05-11 03:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_alter_post_time_create_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='time_create',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 11, 3, 31, 17, 331316)),
        ),
    ]
